/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosDemoStoreRouteImport } from './routes/demos/demo.store'
import { Route as DemosDemoFormSimpleRouteImport } from './routes/demos/demo.form.simple'
import { Route as DemosDemoFormAddressRouteImport } from './routes/demos/demo.form.address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosDemoStoreRoute = DemosDemoStoreRouteImport.update({
  id: '/demos/demo/store',
  path: '/demos/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosDemoFormSimpleRoute = DemosDemoFormSimpleRouteImport.update({
  id: '/demos/demo/form/simple',
  path: '/demos/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosDemoFormAddressRoute = DemosDemoFormAddressRouteImport.update({
  id: '/demos/demo/form/address',
  path: '/demos/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demos/demo/store': typeof DemosDemoStoreRoute
  '/demos/demo/form/address': typeof DemosDemoFormAddressRoute
  '/demos/demo/form/simple': typeof DemosDemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demos/demo/store': typeof DemosDemoStoreRoute
  '/demos/demo/form/address': typeof DemosDemoFormAddressRoute
  '/demos/demo/form/simple': typeof DemosDemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demos/demo/store': typeof DemosDemoStoreRoute
  '/demos/demo/form/address': typeof DemosDemoFormAddressRoute
  '/demos/demo/form/simple': typeof DemosDemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demos/demo/store'
    | '/demos/demo/form/address'
    | '/demos/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demos/demo/store'
    | '/demos/demo/form/address'
    | '/demos/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/demos/demo/store'
    | '/demos/demo/form/address'
    | '/demos/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemosDemoStoreRoute: typeof DemosDemoStoreRoute
  DemosDemoFormAddressRoute: typeof DemosDemoFormAddressRoute
  DemosDemoFormSimpleRoute: typeof DemosDemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/demo/store': {
      id: '/demos/demo/store'
      path: '/demos/demo/store'
      fullPath: '/demos/demo/store'
      preLoaderRoute: typeof DemosDemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/demo/form/simple': {
      id: '/demos/demo/form/simple'
      path: '/demos/demo/form/simple'
      fullPath: '/demos/demo/form/simple'
      preLoaderRoute: typeof DemosDemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/demo/form/address': {
      id: '/demos/demo/form/address'
      path: '/demos/demo/form/address'
      fullPath: '/demos/demo/form/address'
      preLoaderRoute: typeof DemosDemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemosDemoStoreRoute: DemosDemoStoreRoute,
  DemosDemoFormAddressRoute: DemosDemoFormAddressRoute,
  DemosDemoFormSimpleRoute: DemosDemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
